export const promoCodeOrder = {
  "paid_cart":null,
  "id":934,
  "delivery_time":"2017-01-12T10:00:55.000Z",
  "chopsticks":null,
  "utensils":null,
  "plates":null,
  "user_id":584,
  "address_id":769,
  "status_id":null,
  "card_id":null,
  "order_date":null,
  "amount":null,
  "promo_code_id":43,
  "transaction_id":null,
  "pickup":true,
  "bringg_uiid":null,
  "bringg_driver_id":null,
  "promo_code":{
    "id":43,
    "name":"bb1",
    "type":"order",
    "max_number_of_usages":null,
    "expire_date":"2017-01-24T21:59:59.000Z",
    "min_order_sum":null,
    "value":10,
    "bundle_main_id":null,
    "discount_product_id":null,
    "max_discount_products":null,
    "status":true
  },
  "address":{
    "id":769,
    "city":null,
    "street":null,
    "building":null,
    "zip_code":null,
    "company":null,
    "apt_floor":null,
    "notes":null,
    "email":null,
    "user_id":584,
    "is_default":true,
    "out_of_range":true,
    "lat":0,
    "lng":0,
    "distance":8002
  },
  "orders":[
    {
      "id":1233,
      "count":1,
      "product_id":48,
      "is_default":false,
      "address_id":null,
      "cart_order":{
        "cart_id":934,
        "order_id":1233
      },
      "product":{
        "id":48,
        "name":"Honey Walnut Shrimp",
        "price":22.2,
        "short_description":"Damn delicious, large shrimp, raw, peeled and deveined",
        "description":"this dish involves an epic concoction of crispy battered shrimp tossed in a creamy, sweet sauce along with some candy-glazed walnuts. With one pound of shrimp, some walnuts, honey, condensed milk and a bit of mayo, you can easily recreate this on a tight budget.",
        "img":"1afd2c977c76d3d38ff81f143cf4444b.jpg",
        "sorting":3,
        "cook_time":3,
        "category_id":7,
        "badge_id":4,
        "type":"product"
      },
      "order_modifiers":[
        {
          "id":538,
          "value":3,
          "modifier_id":5,
          "order_id":1233,
          "modifier":{
            "id":5,
            "name":"spiciness",
            "price":0,
            "img":null,
            "type":"spiciness"
          }
        },
        {
          "id":539,
          "value":1,
          "modifier_id":14,
          "order_id":1233,
          "modifier":{
            "id":14,
            "name":"Tofu",
            "price":1,
            "img":"3e7ddee3796c3aa06586b763112ceb58.png",
            "type":"single"
          }
        },
        {
          "id":540,
          "value":1,
          "modifier_id":9,
          "order_id":1233,
          "modifier":{
            "id":9,
            "name":"With Gluten, Gluten Free",
            "price":1,
            "img":null,
            "type":"boolean"
          }
        },
        {
          "id":541,
          "value":1,
          "modifier_id":10,
          "order_id":1233,
          "modifier":{
            "id":10,
            "name":"Gluten Free, No Batter",
            "price":1,
            "img":null,
            "type":"boolean"
          }
        }
      ]
    },
    {
      "id":1232,
      "count":1,
      "product_id":54,
      "is_default":true,
      "address_id":null,
      "cart_order":{
        "cart_id":934,
        "order_id":1232
      },
      "product":{
        "id":54,
        "name":"SWEET & SOUR CHICKEN",
        "price":11,
        "short_description":"In a large non-stick skillet, heat oil over medium high heat. Season chicken strips and add to pan. Brown chicken and remove to plate",
        "description":"In a large non-stick skillet, heat oil over medium high heat. Season chicken strips and add to pan. Brown chicken and remove to plate",
        "img":null,
        "sorting":null,
        "cook_time":4,
        "category_id":1,
        "badge_id":4,
        "type":"product"
      },
      "order_modifiers":[
      
      ]
    },
    {
      "id":1234,
      "count":1,
      "product_id":20,
      "is_default":true,
      "address_id":null,
      "cart_order":{
        "cart_id":934,
        "order_id":1234
      },
      "product":{
        "id":20,
        "name":"General Tso Chicken",
        "price":10,
        "short_description":"Served with Rice or Egg Noodles",
        "description":"White meat chicken, lightly battered in a sweet & spicy sauce with broccoli.",
        "img":"bdae752d89571aa14a45d95a069eb816.jpg",
        "sorting":5,
        "cook_time":2,
        "category_id":1,
        "badge_id":2,
        "type":"product"
      },
      "order_modifiers":[
      
      ]
    }
  ],
  "status":null
};

export const promoCodeDiscountWithMaxNumber = {
  "paid_cart":null,
  "id":935,
  "delivery_time":"2017-01-12T09:20:02.000Z",
  "chopsticks":null,
  "utensils":null,
  "plates":null,
  "user_id":585,
  "address_id":770,
  "status_id":null,
  "card_id":null,
  "order_date":null,
  "amount":null,
  "promo_code_id":44,
  "transaction_id":null,
  "pickup":true,
  "bringg_uiid":null,
  "bringg_driver_id":null,
  "user":{
    "id":585,
    "first_name":null,
    "last_name":null,
    "email":"eb48c22ae70390c08a49b0f43ed9f70393cdb972d6347d62d0427bfbfd71a334",
    "phone":null,
    "password":"5c29a959abce4eda5f0e7a4e7ea53dce4fa0f0abbe8eaa63717e2fed5f193d31",
    "token":"c66e968d18cf66f4a2815f8aa5e19c689e21d8306749dc2d050da31235c74e4e",
    "is_active":false,
    "is_catering":false,
    "role":"customer"
  },
  "promo_code":{
    "id":44,
    "name":"bb2",
    "type":"single_product",
    "max_number_of_usages":null,
    "expire_date":"2017-01-25T21:59:59.000Z",
    "min_order_sum":null,
    "value":5,
    "bundle_main_id":null,
    "discount_product_id":54,
    "max_discount_products":2,
    "status":true
  },
  "address":{
    "id":770,
    "city":null,
    "street":null,
    "building":null,
    "zip_code":null,
    "company":null,
    "apt_floor":null,
    "notes":null,
    "email":null,
    "user_id":585,
    "is_default":true,
    "out_of_range":true,
    "lat":0,
    "lng":0,
    "distance":8002
  },
  "orders":[
    {
      "id":1236,
      "count":1,
      "product_id":48,
      "is_default":false,
      "address_id":null,
      "cart_order":{
        "cart_id":935,
        "order_id":1236
      },
      "product":{
        "id":48,
        "name":"Honey Walnut Shrimp",
        "price":22.2,
        "short_description":"Damn delicious, large shrimp, raw, peeled and deveined",
        "description":"this dish involves an epic concoction of crispy battered shrimp tossed in a creamy, sweet sauce along with some candy-glazed walnuts. With one pound of shrimp, some walnuts, honey, condensed milk and a bit of mayo, you can easily recreate this on a tight budget.",
        "img":"1afd2c977c76d3d38ff81f143cf4444b.jpg",
        "sorting":3,
        "cook_time":3,
        "category_id":7,
        "badge_id":4,
        "type":"product"
      },
      "order_modifiers":[
        {
          "id":542,
          "value":2,
          "modifier_id":5,
          "order_id":1236,
          "modifier":{
            "id":5,
            "name":"spiciness",
            "price":0,
            "img":null,
            "type":"spiciness"
          }
        },
        {
          "id":543,
          "value":1,
          "modifier_id":14,
          "order_id":1236,
          "modifier":{
            "id":14,
            "name":"Tofu",
            "price":1,
            "img":"3e7ddee3796c3aa06586b763112ceb58.png",
            "type":"single"
          }
        },
        {
          "id":544,
          "value":1,
          "modifier_id":9,
          "order_id":1236,
          "modifier":{
            "id":9,
            "name":"With Gluten, Gluten Free",
            "price":1,
            "img":null,
            "type":"boolean"
          }
        },
        {
          "id":545,
          "value":1,
          "modifier_id":10,
          "order_id":1236,
          "modifier":{
            "id":10,
            "name":"Gluten Free, No Batter",
            "price":1,
            "img":null,
            "type":"boolean"
          }
        }
      ]
    },
    {
      "id":1235,
      "count":3,
      "product_id":54,
      "is_default":true,
      "address_id":null,
      "cart_order":{
        "cart_id":935,
        "order_id":1235
      },
      "product":{
        "id":54,
        "name":"SWEET & SOUR CHICKEN",
        "price":11,
        "short_description":"In a large non-stick skillet, heat oil over medium high heat. Season chicken strips and add to pan. Brown chicken and remove to plate",
        "description":"In a large non-stick skillet, heat oil over medium high heat. Season chicken strips and add to pan. Brown chicken and remove to plate",
        "img":null,
        "sorting":null,
        "cook_time":4,
        "category_id":1,
        "badge_id":4,
        "type":"product"
      },
      "order_modifiers":[
      
      ]
    },
    {
      "id":1237,
      "count":1,
      "product_id":20,
      "is_default":true,
      "address_id":null,
      "cart_order":{
        "cart_id":935,
        "order_id":1237
      },
      "product":{
        "id":20,
        "name":"General Tso Chicken",
        "price":10,
        "short_description":"Served with Rice or Egg Noodles",
        "description":"White meat chicken, lightly battered in a sweet & spicy sauce with broccoli.",
        "img":"bdae752d89571aa14a45d95a069eb816.jpg",
        "sorting":5,
        "cook_time":2,
        "category_id":1,
        "badge_id":2,
        "type":"product"
      },
      "order_modifiers":[
      
      ]
    }
  ],
  "status":null
};

export const promoCodeDiscountWOMaxNumber = {
  "paid_cart":null,
  "id":935,
  "delivery_time":"2017-01-12T09:20:02.000Z",
  "chopsticks":null,
  "utensils":null,
  "plates":null,
  "user_id":585,
  "address_id":770,
  "status_id":null,
  "card_id":null,
  "order_date":null,
  "amount":null,
  "promo_code_id":44,
  "transaction_id":null,
  "pickup":true,
  "bringg_uiid":null,
  "bringg_driver_id":null,
  "user":{
    "id":585,
    "first_name":null,
    "last_name":null,
    "email":"eb48c22ae70390c08a49b0f43ed9f70393cdb972d6347d62d0427bfbfd71a334",
    "phone":null,
    "password":"5c29a959abce4eda5f0e7a4e7ea53dce4fa0f0abbe8eaa63717e2fed5f193d31",
    "token":"c66e968d18cf66f4a2815f8aa5e19c689e21d8306749dc2d050da31235c74e4e",
    "is_active":false,
    "is_catering":false,
    "role":"customer"
  },
  "promo_code":{
    "id":44,
    "name":"bb2",
    "type":"single_product",
    "max_number_of_usages":null,
    "expire_date":"2017-01-25T21:59:59.000Z",
    "min_order_sum":null,
    "value":5,
    "bundle_main_id":null,
    "discount_product_id":54,
    "max_discount_products":null,
    "status":true
  },
  "address":{
    "id":770,
    "city":null,
    "street":null,
    "building":null,
    "zip_code":null,
    "company":null,
    "apt_floor":null,
    "notes":null,
    "email":null,
    "user_id":585,
    "is_default":true,
    "out_of_range":true,
    "lat":0,
    "lng":0,
    "distance":8002
  },
  "orders":[
    {
      "id":1236,
      "count":1,
      "product_id":48,
      "is_default":false,
      "address_id":null,
      "cart_order":{
        "cart_id":935,
        "order_id":1236
      },
      "product":{
        "id":48,
        "name":"Honey Walnut Shrimp",
        "price":22.2,
        "short_description":"Damn delicious, large shrimp, raw, peeled and deveined",
        "description":"this dish involves an epic concoction of crispy battered shrimp tossed in a creamy, sweet sauce along with some candy-glazed walnuts. With one pound of shrimp, some walnuts, honey, condensed milk and a bit of mayo, you can easily recreate this on a tight budget.",
        "img":"1afd2c977c76d3d38ff81f143cf4444b.jpg",
        "sorting":3,
        "cook_time":3,
        "category_id":7,
        "badge_id":4,
        "type":"product"
      },
      "order_modifiers":[
        {
          "id":542,
          "value":2,
          "modifier_id":5,
          "order_id":1236,
          "modifier":{
            "id":5,
            "name":"spiciness",
            "price":0,
            "img":null,
            "type":"spiciness"
          }
        },
        {
          "id":543,
          "value":1,
          "modifier_id":14,
          "order_id":1236,
          "modifier":{
            "id":14,
            "name":"Tofu",
            "price":1,
            "img":"3e7ddee3796c3aa06586b763112ceb58.png",
            "type":"single"
          }
        },
        {
          "id":544,
          "value":1,
          "modifier_id":9,
          "order_id":1236,
          "modifier":{
            "id":9,
            "name":"With Gluten, Gluten Free",
            "price":1,
            "img":null,
            "type":"boolean"
          }
        },
        {
          "id":545,
          "value":1,
          "modifier_id":10,
          "order_id":1236,
          "modifier":{
            "id":10,
            "name":"Gluten Free, No Batter",
            "price":1,
            "img":null,
            "type":"boolean"
          }
        }
      ]
    },
    {
      "id":1235,
      "count":3,
      "product_id":54,
      "is_default":true,
      "address_id":null,
      "cart_order":{
        "cart_id":935,
        "order_id":1235
      },
      "product":{
        "id":54,
        "name":"SWEET & SOUR CHICKEN",
        "price":11,
        "short_description":"In a large non-stick skillet, heat oil over medium high heat. Season chicken strips and add to pan. Brown chicken and remove to plate",
        "description":"In a large non-stick skillet, heat oil over medium high heat. Season chicken strips and add to pan. Brown chicken and remove to plate",
        "img":null,
        "sorting":null,
        "cook_time":4,
        "category_id":1,
        "badge_id":4,
        "type":"product"
      },
      "order_modifiers":[
      
      ]
    },
    {
      "id":1237,
      "count":1,
      "product_id":20,
      "is_default":true,
      "address_id":null,
      "cart_order":{
        "cart_id":935,
        "order_id":1237
      },
      "product":{
        "id":20,
        "name":"General Tso Chicken",
        "price":10,
        "short_description":"Served with Rice or Egg Noodles",
        "description":"White meat chicken, lightly battered in a sweet & spicy sauce with broccoli.",
        "img":"bdae752d89571aa14a45d95a069eb816.jpg",
        "sorting":5,
        "cook_time":2,
        "category_id":1,
        "badge_id":2,
        "type":"product"
      },
      "order_modifiers":[
      
      ]
    }
  ],
  "status":null
};

export const promoCodeDiscountWithMaxNumberWODiscountValue = {
  "paid_cart":null,
  "id":935,
  "delivery_time":"2017-01-12T09:20:02.000Z",
  "chopsticks":null,
  "utensils":null,
  "plates":null,
  "user_id":585,
  "address_id":770,
  "status_id":null,
  "card_id":null,
  "order_date":null,
  "amount":null,
  "promo_code_id":44,
  "transaction_id":null,
  "pickup":true,
  "bringg_uiid":null,
  "bringg_driver_id":null,
  "user":{
    "id":585,
    "first_name":null,
    "last_name":null,
    "email":"eb48c22ae70390c08a49b0f43ed9f70393cdb972d6347d62d0427bfbfd71a334",
    "phone":null,
    "password":"5c29a959abce4eda5f0e7a4e7ea53dce4fa0f0abbe8eaa63717e2fed5f193d31",
    "token":"c66e968d18cf66f4a2815f8aa5e19c689e21d8306749dc2d050da31235c74e4e",
    "is_active":false,
    "is_catering":false,
    "role":"customer"
  },
  "promo_code":{
    "id":44,
    "name":"bb2",
    "type":"single_product",
    "max_number_of_usages":null,
    "expire_date":"2017-01-25T21:59:59.000Z",
    "min_order_sum":null,
    "value":null,
    "bundle_main_id":null,
    "discount_product_id":54,
    "max_discount_products":2,
    "status":true
  },
  "address":{
    "id":770,
    "city":null,
    "street":null,
    "building":null,
    "zip_code":null,
    "company":null,
    "apt_floor":null,
    "notes":null,
    "email":null,
    "user_id":585,
    "is_default":true,
    "out_of_range":true,
    "lat":0,
    "lng":0,
    "distance":8002
  },
  "orders":[
    {
      "id":1236,
      "count":1,
      "product_id":48,
      "is_default":false,
      "address_id":null,
      "cart_order":{
        "cart_id":935,
        "order_id":1236
      },
      "product":{
        "id":48,
        "name":"Honey Walnut Shrimp",
        "price":22.2,
        "short_description":"Damn delicious, large shrimp, raw, peeled and deveined",
        "description":"this dish involves an epic concoction of crispy battered shrimp tossed in a creamy, sweet sauce along with some candy-glazed walnuts. With one pound of shrimp, some walnuts, honey, condensed milk and a bit of mayo, you can easily recreate this on a tight budget.",
        "img":"1afd2c977c76d3d38ff81f143cf4444b.jpg",
        "sorting":3,
        "cook_time":3,
        "category_id":7,
        "badge_id":4,
        "type":"product"
      },
      "order_modifiers":[
        {
          "id":542,
          "value":2,
          "modifier_id":5,
          "order_id":1236,
          "modifier":{
            "id":5,
            "name":"spiciness",
            "price":0,
            "img":null,
            "type":"spiciness"
          }
        },
        {
          "id":543,
          "value":1,
          "modifier_id":14,
          "order_id":1236,
          "modifier":{
            "id":14,
            "name":"Tofu",
            "price":1,
            "img":"3e7ddee3796c3aa06586b763112ceb58.png",
            "type":"single"
          }
        },
        {
          "id":544,
          "value":1,
          "modifier_id":9,
          "order_id":1236,
          "modifier":{
            "id":9,
            "name":"With Gluten, Gluten Free",
            "price":1,
            "img":null,
            "type":"boolean"
          }
        },
        {
          "id":545,
          "value":1,
          "modifier_id":10,
          "order_id":1236,
          "modifier":{
            "id":10,
            "name":"Gluten Free, No Batter",
            "price":1,
            "img":null,
            "type":"boolean"
          }
        }
      ]
    },
    {
      "id":1235,
      "count":3,
      "product_id":54,
      "is_default":true,
      "address_id":null,
      "cart_order":{
        "cart_id":935,
        "order_id":1235
      },
      "product":{
        "id":54,
        "name":"SWEET & SOUR CHICKEN",
        "price":11,
        "short_description":"In a large non-stick skillet, heat oil over medium high heat. Season chicken strips and add to pan. Brown chicken and remove to plate",
        "description":"In a large non-stick skillet, heat oil over medium high heat. Season chicken strips and add to pan. Brown chicken and remove to plate",
        "img":null,
        "sorting":null,
        "cook_time":4,
        "category_id":1,
        "badge_id":4,
        "type":"product"
      },
      "order_modifiers":[
      
      ]
    },
    {
      "id":1237,
      "count":1,
      "product_id":20,
      "is_default":true,
      "address_id":null,
      "cart_order":{
        "cart_id":935,
        "order_id":1237
      },
      "product":{
        "id":20,
        "name":"General Tso Chicken",
        "price":10,
        "short_description":"Served with Rice or Egg Noodles",
        "description":"White meat chicken, lightly battered in a sweet & spicy sauce with broccoli.",
        "img":"bdae752d89571aa14a45d95a069eb816.jpg",
        "sorting":5,
        "cook_time":2,
        "category_id":1,
        "badge_id":2,
        "type":"product"
      },
      "order_modifiers":[
      
      ]
    }
  ],
  "status":null
};

export const promoCodeDiscountWOMaxNumberWODiscountValue = {
  "paid_cart":null,
  "id":935,
  "delivery_time":"2017-01-12T09:20:02.000Z",
  "chopsticks":null,
  "utensils":null,
  "plates":null,
  "user_id":585,
  "address_id":770,
  "status_id":null,
  "card_id":null,
  "order_date":null,
  "amount":null,
  "promo_code_id":44,
  "transaction_id":null,
  "pickup":true,
  "bringg_uiid":null,
  "bringg_driver_id":null,
  "user":{
    "id":585,
    "first_name":null,
    "last_name":null,
    "email":"eb48c22ae70390c08a49b0f43ed9f70393cdb972d6347d62d0427bfbfd71a334",
    "phone":null,
    "password":"5c29a959abce4eda5f0e7a4e7ea53dce4fa0f0abbe8eaa63717e2fed5f193d31",
    "token":"c66e968d18cf66f4a2815f8aa5e19c689e21d8306749dc2d050da31235c74e4e",
    "is_active":false,
    "is_catering":false,
    "role":"customer"
  },
  "promo_code":{
    "id":44,
    "name":"bb2",
    "type":"single_product",
    "max_number_of_usages":null,
    "expire_date":"2017-01-25T21:59:59.000Z",
    "min_order_sum":null,
    "value":null,
    "bundle_main_id":null,
    "discount_product_id":54,
    "max_discount_products":null,
    "status":true
  },
  "address":{
    "id":770,
    "city":null,
    "street":null,
    "building":null,
    "zip_code":null,
    "company":null,
    "apt_floor":null,
    "notes":null,
    "email":null,
    "user_id":585,
    "is_default":true,
    "out_of_range":true,
    "lat":0,
    "lng":0,
    "distance":8002
  },
  "orders":[
    {
      "id":1236,
      "count":1,
      "product_id":48,
      "is_default":false,
      "address_id":null,
      "cart_order":{
        "cart_id":935,
        "order_id":1236
      },
      "product":{
        "id":48,
        "name":"Honey Walnut Shrimp",
        "price":22.2,
        "short_description":"Damn delicious, large shrimp, raw, peeled and deveined",
        "description":"this dish involves an epic concoction of crispy battered shrimp tossed in a creamy, sweet sauce along with some candy-glazed walnuts. With one pound of shrimp, some walnuts, honey, condensed milk and a bit of mayo, you can easily recreate this on a tight budget.",
        "img":"1afd2c977c76d3d38ff81f143cf4444b.jpg",
        "sorting":3,
        "cook_time":3,
        "category_id":7,
        "badge_id":4,
        "type":"product"
      },
      "order_modifiers":[
        {
          "id":542,
          "value":2,
          "modifier_id":5,
          "order_id":1236,
          "modifier":{
            "id":5,
            "name":"spiciness",
            "price":0,
            "img":null,
            "type":"spiciness"
          }
        },
        {
          "id":543,
          "value":1,
          "modifier_id":14,
          "order_id":1236,
          "modifier":{
            "id":14,
            "name":"Tofu",
            "price":1,
            "img":"3e7ddee3796c3aa06586b763112ceb58.png",
            "type":"single"
          }
        },
        {
          "id":544,
          "value":1,
          "modifier_id":9,
          "order_id":1236,
          "modifier":{
            "id":9,
            "name":"With Gluten, Gluten Free",
            "price":1,
            "img":null,
            "type":"boolean"
          }
        },
        {
          "id":545,
          "value":1,
          "modifier_id":10,
          "order_id":1236,
          "modifier":{
            "id":10,
            "name":"Gluten Free, No Batter",
            "price":1,
            "img":null,
            "type":"boolean"
          }
        }
      ]
    },
    {
      "id":1235,
      "count":3,
      "product_id":54,
      "is_default":true,
      "address_id":null,
      "cart_order":{
        "cart_id":935,
        "order_id":1235
      },
      "product":{
        "id":54,
        "name":"SWEET & SOUR CHICKEN",
        "price":11,
        "short_description":"In a large non-stick skillet, heat oil over medium high heat. Season chicken strips and add to pan. Brown chicken and remove to plate",
        "description":"In a large non-stick skillet, heat oil over medium high heat. Season chicken strips and add to pan. Brown chicken and remove to plate",
        "img":null,
        "sorting":null,
        "cook_time":4,
        "category_id":1,
        "badge_id":4,
        "type":"product"
      },
      "order_modifiers":[
      
      ]
    },
    {
      "id":1237,
      "count":5,
      "product_id":20,
      "is_default":true,
      "address_id":null,
      "cart_order":{
        "cart_id":935,
        "order_id":1237
      },
      "product":{
        "id":20,
        "name":"General Tso Chicken",
        "price":10,
        "short_description":"Served with Rice or Egg Noodles",
        "description":"White meat chicken, lightly battered in a sweet & spicy sauce with broccoli.",
        "img":"bdae752d89571aa14a45d95a069eb816.jpg",
        "sorting":5,
        "cook_time":2,
        "category_id":1,
        "badge_id":2,
        "type":"product"
      },
      "order_modifiers":[
      
      ]
    }
  ],
  "status":null
};

export const promoCodeBundleWithMaxNumber = {
  "paid_cart":null,
  "id":938,
  "delivery_time":"2017-01-12T10:00:33.000Z",
  "chopsticks":null,
  "utensils":null,
  "plates":null,
  "user_id":588,
  "address_id":773,
  "status_id":null,
  "card_id":null,
  "order_date":null,
  "amount":null,
  "promo_code_id":46,
  "transaction_id":null,
  "pickup":true,
  "bringg_uiid":null,
  "bringg_driver_id":null,
  "user":{
    "id":588,
    "first_name":null,
    "last_name":null,
    "email":"6610c1d5916bca77cb208af28831fd093d09bb6faf1c2fa0b15ae7eed9e0c841",
    "phone":null,
    "password":"5c29a959abce4eda5f0e7a4e7ea53dce4fa0f0abbe8eaa63717e2fed5f193d31",
    "token":"84fa2d0895e8b9b003fd89abea4b87266b33d76b9f26ab84e83872b68e243d93",
    "is_active":false,
    "is_catering":false,
    "role":"customer"
  },
  "promo_code":{
    "id":46,
    "name":"bb4",
    "type":"bundle",
    "max_number_of_usages":null,
    "expire_date":"2017-01-12T21:59:59.000Z",
    "min_order_sum":null,
    "value":5,
    "bundle_main_id":20,
    "discount_product_id":54,
    "max_discount_products":2,
    "status":true
  },
  "address":{
    "id":773,
    "city":null,
    "street":null,
    "building":null,
    "zip_code":null,
    "company":null,
    "apt_floor":null,
    "notes":null,
    "email":null,
    "user_id":588,
    "is_default":true,
    "out_of_range":true,
    "lat":0,
    "lng":0,
    "distance":8002
  },
  "orders":[
    {
      "id":1241,
      "count":1,
      "product_id":48,
      "is_default":false,
      "address_id":null,
      "cart_order":{
        "cart_id":938,
        "order_id":1241
      },
      "product":{
        "id":48,
        "name":"Honey Walnut Shrimp",
        "price":22.2,
        "short_description":"Damn delicious, large shrimp, raw, peeled and deveined",
        "description":"this dish involves an epic concoction of crispy battered shrimp tossed in a creamy, sweet sauce along with some candy-glazed walnuts. With one pound of shrimp, some walnuts, honey, condensed milk and a bit of mayo, you can easily recreate this on a tight budget.",
        "img":"1afd2c977c76d3d38ff81f143cf4444b.jpg",
        "sorting":3,
        "cook_time":3,
        "category_id":7,
        "badge_id":4,
        "type":"product"
      },
      "order_modifiers":[
        {
          "id":547,
          "value":1,
          "modifier_id":14,
          "order_id":1241,
          "modifier":{
            "id":14,
            "name":"Tofu",
            "price":1,
            "img":"3e7ddee3796c3aa06586b763112ceb58.png",
            "type":"single"
          }
        },
        {
          "id":548,
          "value":1,
          "modifier_id":9,
          "order_id":1241,
          "modifier":{
            "id":9,
            "name":"With Gluten, Gluten Free",
            "price":1,
            "img":null,
            "type":"boolean"
          }
        },
        {
          "id":549,
          "value":1,
          "modifier_id":10,
          "order_id":1241,
          "modifier":{
            "id":10,
            "name":"Gluten Free, No Batter",
            "price":1,
            "img":null,
            "type":"boolean"
          }
        }
      ]
    },
    {
      "id":1240,
      "count":3,
      "product_id":54,
      "is_default":true,
      "address_id":null,
      "cart_order":{
        "cart_id":938,
        "order_id":1240
      },
      "product":{
        "id":54,
        "name":"SWEET & SOUR CHICKEN",
        "price":11,
        "short_description":"In a large non-stick skillet, heat oil over medium high heat. Season chicken strips and add to pan. Brown chicken and remove to plate",
        "description":"In a large non-stick skillet, heat oil over medium high heat. Season chicken strips and add to pan. Brown chicken and remove to plate",
        "img":"97ada39d31abc21ad4992d0b7f9d2404.jpg",
        "sorting":null,
        "cook_time":4,
        "category_id":1,
        "badge_id":4,
        "type":"product"
      },
      "order_modifiers":[
      
      ]
    },
    {
      "id":1242,
      "count":1,
      "product_id":20,
      "is_default":true,
      "address_id":null,
      "cart_order":{
        "cart_id":938,
        "order_id":1242
      },
      "product":{
        "id":20,
        "name":"General Tso Chicken",
        "price":10,
        "short_description":"Served with Rice or Egg Noodles",
        "description":"White meat chicken, lightly battered in a sweet & spicy sauce with broccoli.",
        "img":"bdae752d89571aa14a45d95a069eb816.jpg",
        "sorting":5,
        "cook_time":2,
        "category_id":1,
        "badge_id":2,
        "type":"product"
      },
      "order_modifiers":[
      
      ]
    }
  ],
  "status":null
};

export const promoCodeBundleWOMaxNumber = {
  "paid_cart":null,
  "id":938,
  "delivery_time":"2017-01-12T10:00:33.000Z",
  "chopsticks":null,
  "utensils":null,
  "plates":null,
  "user_id":588,
  "address_id":773,
  "status_id":null,
  "card_id":null,
  "order_date":null,
  "amount":null,
  "promo_code_id":46,
  "transaction_id":null,
  "pickup":true,
  "bringg_uiid":null,
  "bringg_driver_id":null,
  "user":{
    "id":588,
    "first_name":null,
    "last_name":null,
    "email":"6610c1d5916bca77cb208af28831fd093d09bb6faf1c2fa0b15ae7eed9e0c841",
    "phone":null,
    "password":"5c29a959abce4eda5f0e7a4e7ea53dce4fa0f0abbe8eaa63717e2fed5f193d31",
    "token":"84fa2d0895e8b9b003fd89abea4b87266b33d76b9f26ab84e83872b68e243d93",
    "is_active":false,
    "is_catering":false,
    "role":"customer"
  },
  "promo_code":{
    "id":46,
    "name":"bb4",
    "type":"bundle",
    "max_number_of_usages":null,
    "expire_date":"2017-01-12T21:59:59.000Z",
    "min_order_sum":null,
    "value":5,
    "bundle_main_id":20,
    "discount_product_id":54,
    "max_discount_products":null,
    "status":true
  },
  "address":{
    "id":773,
    "city":null,
    "street":null,
    "building":null,
    "zip_code":null,
    "company":null,
    "apt_floor":null,
    "notes":null,
    "email":null,
    "user_id":588,
    "is_default":true,
    "out_of_range":true,
    "lat":0,
    "lng":0,
    "distance":8002
  },
  "orders":[
    {
      "id":1241,
      "count":1,
      "product_id":48,
      "is_default":false,
      "address_id":null,
      "cart_order":{
        "cart_id":938,
        "order_id":1241
      },
      "product":{
        "id":48,
        "name":"Honey Walnut Shrimp",
        "price":22.2,
        "short_description":"Damn delicious, large shrimp, raw, peeled and deveined",
        "description":"this dish involves an epic concoction of crispy battered shrimp tossed in a creamy, sweet sauce along with some candy-glazed walnuts. With one pound of shrimp, some walnuts, honey, condensed milk and a bit of mayo, you can easily recreate this on a tight budget.",
        "img":"1afd2c977c76d3d38ff81f143cf4444b.jpg",
        "sorting":3,
        "cook_time":3,
        "category_id":7,
        "badge_id":4,
        "type":"product"
      },
      "order_modifiers":[
        {
          "id":547,
          "value":1,
          "modifier_id":14,
          "order_id":1241,
          "modifier":{
            "id":14,
            "name":"Tofu",
            "price":1,
            "img":"3e7ddee3796c3aa06586b763112ceb58.png",
            "type":"single"
          }
        },
        {
          "id":548,
          "value":1,
          "modifier_id":9,
          "order_id":1241,
          "modifier":{
            "id":9,
            "name":"With Gluten, Gluten Free",
            "price":1,
            "img":null,
            "type":"boolean"
          }
        },
        {
          "id":549,
          "value":1,
          "modifier_id":10,
          "order_id":1241,
          "modifier":{
            "id":10,
            "name":"Gluten Free, No Batter",
            "price":1,
            "img":null,
            "type":"boolean"
          }
        }
      ]
    },
    {
      "id":1240,
      "count":3,
      "product_id":54,
      "is_default":true,
      "address_id":null,
      "cart_order":{
        "cart_id":938,
        "order_id":1240
      },
      "product":{
        "id":54,
        "name":"SWEET & SOUR CHICKEN",
        "price":11,
        "short_description":"In a large non-stick skillet, heat oil over medium high heat. Season chicken strips and add to pan. Brown chicken and remove to plate",
        "description":"In a large non-stick skillet, heat oil over medium high heat. Season chicken strips and add to pan. Brown chicken and remove to plate",
        "img":"97ada39d31abc21ad4992d0b7f9d2404.jpg",
        "sorting":null,
        "cook_time":4,
        "category_id":1,
        "badge_id":4,
        "type":"product"
      },
      "order_modifiers":[
      
      ]
    },
    {
      "id":1242,
      "count":1,
      "product_id":20,
      "is_default":true,
      "address_id":null,
      "cart_order":{
        "cart_id":938,
        "order_id":1242
      },
      "product":{
        "id":20,
        "name":"General Tso Chicken",
        "price":10,
        "short_description":"Served with Rice or Egg Noodles",
        "description":"White meat chicken, lightly battered in a sweet & spicy sauce with broccoli.",
        "img":"bdae752d89571aa14a45d95a069eb816.jpg",
        "sorting":5,
        "cook_time":2,
        "category_id":1,
        "badge_id":2,
        "type":"product"
      },
      "order_modifiers":[
      
      ]
    }
  ],
  "status":null
};

export const promoCodeBundleWithMaxNumberWODiscountValue = {
  "paid_cart":null,
  "id":938,
  "delivery_time":"2017-01-12T10:00:33.000Z",
  "chopsticks":null,
  "utensils":null,
  "plates":null,
  "user_id":588,
  "address_id":773,
  "status_id":null,
  "card_id":null,
  "order_date":null,
  "amount":null,
  "promo_code_id":46,
  "transaction_id":null,
  "pickup":true,
  "bringg_uiid":null,
  "bringg_driver_id":null,
  "user":{
    "id":588,
    "first_name":null,
    "last_name":null,
    "email":"6610c1d5916bca77cb208af28831fd093d09bb6faf1c2fa0b15ae7eed9e0c841",
    "phone":null,
    "password":"5c29a959abce4eda5f0e7a4e7ea53dce4fa0f0abbe8eaa63717e2fed5f193d31",
    "token":"84fa2d0895e8b9b003fd89abea4b87266b33d76b9f26ab84e83872b68e243d93",
    "is_active":false,
    "is_catering":false,
    "role":"customer"
  },
  "promo_code":{
    "id":46,
    "name":"bb4",
    "type":"bundle",
    "max_number_of_usages":null,
    "expire_date":"2017-01-12T21:59:59.000Z",
    "min_order_sum":null,
    "value":null,
    "bundle_main_id":20,
    "discount_product_id":54,
    "max_discount_products":2,
    "status":true
  },
  "address":{
    "id":773,
    "city":null,
    "street":null,
    "building":null,
    "zip_code":null,
    "company":null,
    "apt_floor":null,
    "notes":null,
    "email":null,
    "user_id":588,
    "is_default":true,
    "out_of_range":true,
    "lat":0,
    "lng":0,
    "distance":8002
  },
  "orders":[
    {
      "id":1241,
      "count":1,
      "product_id":48,
      "is_default":false,
      "address_id":null,
      "cart_order":{
        "cart_id":938,
        "order_id":1241
      },
      "product":{
        "id":48,
        "name":"Honey Walnut Shrimp",
        "price":22.2,
        "short_description":"Damn delicious, large shrimp, raw, peeled and deveined",
        "description":"this dish involves an epic concoction of crispy battered shrimp tossed in a creamy, sweet sauce along with some candy-glazed walnuts. With one pound of shrimp, some walnuts, honey, condensed milk and a bit of mayo, you can easily recreate this on a tight budget.",
        "img":"1afd2c977c76d3d38ff81f143cf4444b.jpg",
        "sorting":3,
        "cook_time":3,
        "category_id":7,
        "badge_id":4,
        "type":"product"
      },
      "order_modifiers":[
        {
          "id":547,
          "value":1,
          "modifier_id":14,
          "order_id":1241,
          "modifier":{
            "id":14,
            "name":"Tofu",
            "price":1,
            "img":"3e7ddee3796c3aa06586b763112ceb58.png",
            "type":"single"
          }
        },
        {
          "id":548,
          "value":1,
          "modifier_id":9,
          "order_id":1241,
          "modifier":{
            "id":9,
            "name":"With Gluten, Gluten Free",
            "price":1,
            "img":null,
            "type":"boolean"
          }
        },
        {
          "id":549,
          "value":1,
          "modifier_id":10,
          "order_id":1241,
          "modifier":{
            "id":10,
            "name":"Gluten Free, No Batter",
            "price":1,
            "img":null,
            "type":"boolean"
          }
        }
      ]
    },
    {
      "id":1240,
      "count":3,
      "product_id":54,
      "is_default":true,
      "address_id":null,
      "cart_order":{
        "cart_id":938,
        "order_id":1240
      },
      "product":{
        "id":54,
        "name":"SWEET & SOUR CHICKEN",
        "price":11,
        "short_description":"In a large non-stick skillet, heat oil over medium high heat. Season chicken strips and add to pan. Brown chicken and remove to plate",
        "description":"In a large non-stick skillet, heat oil over medium high heat. Season chicken strips and add to pan. Brown chicken and remove to plate",
        "img":"97ada39d31abc21ad4992d0b7f9d2404.jpg",
        "sorting":null,
        "cook_time":4,
        "category_id":1,
        "badge_id":4,
        "type":"product"
      },
      "order_modifiers":[
      
      ]
    },
    {
      "id":1242,
      "count":1,
      "product_id":20,
      "is_default":true,
      "address_id":null,
      "cart_order":{
        "cart_id":938,
        "order_id":1242
      },
      "product":{
        "id":20,
        "name":"General Tso Chicken",
        "price":10,
        "short_description":"Served with Rice or Egg Noodles",
        "description":"White meat chicken, lightly battered in a sweet & spicy sauce with broccoli.",
        "img":"bdae752d89571aa14a45d95a069eb816.jpg",
        "sorting":5,
        "cook_time":2,
        "category_id":1,
        "badge_id":2,
        "type":"product"
      },
      "order_modifiers":[
      
      ]
    }
  ],
  "status":null
};

export const promoCodeBundleWOMaxNumberWODiscountValue = {
  "paid_cart":null,
  "id":938,
  "delivery_time":"2017-01-12T10:00:33.000Z",
  "chopsticks":null,
  "utensils":null,
  "plates":null,
  "user_id":588,
  "address_id":773,
  "status_id":null,
  "card_id":null,
  "order_date":null,
  "amount":null,
  "promo_code_id":46,
  "transaction_id":null,
  "pickup":true,
  "bringg_uiid":null,
  "bringg_driver_id":null,
  "user":{
    "id":588,
    "first_name":null,
    "last_name":null,
    "email":"6610c1d5916bca77cb208af28831fd093d09bb6faf1c2fa0b15ae7eed9e0c841",
    "phone":null,
    "password":"5c29a959abce4eda5f0e7a4e7ea53dce4fa0f0abbe8eaa63717e2fed5f193d31",
    "token":"84fa2d0895e8b9b003fd89abea4b87266b33d76b9f26ab84e83872b68e243d93",
    "is_active":false,
    "is_catering":false,
    "role":"customer"
  },
  "promo_code":{
    "id":46,
    "name":"bb4",
    "type":"bundle",
    "max_number_of_usages":null,
    "expire_date":"2017-01-12T21:59:59.000Z",
    "min_order_sum":null,
    "value":null,
    "bundle_main_id":20,
    "discount_product_id":54,
    "max_discount_products":null,
    "status":true
  },
  "address":{
    "id":773,
    "city":null,
    "street":null,
    "building":null,
    "zip_code":null,
    "company":null,
    "apt_floor":null,
    "notes":null,
    "email":null,
    "user_id":588,
    "is_default":true,
    "out_of_range":true,
    "lat":0,
    "lng":0,
    "distance":8002
  },
  "orders":[
    {
      "id":1241,
      "count":1,
      "product_id":48,
      "is_default":false,
      "address_id":null,
      "cart_order":{
        "cart_id":938,
        "order_id":1241
      },
      "product":{
        "id":48,
        "name":"Honey Walnut Shrimp",
        "price":22.2,
        "short_description":"Damn delicious, large shrimp, raw, peeled and deveined",
        "description":"this dish involves an epic concoction of crispy battered shrimp tossed in a creamy, sweet sauce along with some candy-glazed walnuts. With one pound of shrimp, some walnuts, honey, condensed milk and a bit of mayo, you can easily recreate this on a tight budget.",
        "img":"1afd2c977c76d3d38ff81f143cf4444b.jpg",
        "sorting":3,
        "cook_time":3,
        "category_id":7,
        "badge_id":4,
        "type":"product"
      },
      "order_modifiers":[
        {
          "id":547,
          "value":1,
          "modifier_id":14,
          "order_id":1241,
          "modifier":{
            "id":14,
            "name":"Tofu",
            "price":1,
            "img":"3e7ddee3796c3aa06586b763112ceb58.png",
            "type":"single"
          }
        },
        {
          "id":548,
          "value":1,
          "modifier_id":9,
          "order_id":1241,
          "modifier":{
            "id":9,
            "name":"With Gluten, Gluten Free",
            "price":1,
            "img":null,
            "type":"boolean"
          }
        },
        {
          "id":549,
          "value":1,
          "modifier_id":10,
          "order_id":1241,
          "modifier":{
            "id":10,
            "name":"Gluten Free, No Batter",
            "price":1,
            "img":null,
            "type":"boolean"
          }
        }
      ]
    },
    {
      "id":1240,
      "count":3,
      "product_id":54,
      "is_default":true,
      "address_id":null,
      "cart_order":{
        "cart_id":938,
        "order_id":1240
      },
      "product":{
        "id":54,
        "name":"SWEET & SOUR CHICKEN",
        "price":11,
        "short_description":"In a large non-stick skillet, heat oil over medium high heat. Season chicken strips and add to pan. Brown chicken and remove to plate",
        "description":"In a large non-stick skillet, heat oil over medium high heat. Season chicken strips and add to pan. Brown chicken and remove to plate",
        "img":"97ada39d31abc21ad4992d0b7f9d2404.jpg",
        "sorting":null,
        "cook_time":4,
        "category_id":1,
        "badge_id":4,
        "type":"product"
      },
      "order_modifiers":[
      
      ]
    },
    {
      "id":1242,
      "count":5,
      "product_id":20,
      "is_default":true,
      "address_id":null,
      "cart_order":{
        "cart_id":938,
        "order_id":1242
      },
      "product":{
        "id":20,
        "name":"General Tso Chicken",
        "price":10,
        "short_description":"Served with Rice or Egg Noodles",
        "description":"White meat chicken, lightly battered in a sweet & spicy sauce with broccoli.",
        "img":"bdae752d89571aa14a45d95a069eb816.jpg",
        "sorting":5,
        "cook_time":2,
        "category_id":1,
        "badge_id":2,
        "type":"product"
      },
      "order_modifiers":[
      
      ]
    }
  ],
  "status":null
};