import React, {Component, PropTypes} from 'react';
import { connect } from 'react-redux';
import { Header } from 'components';
import { push } from 'react-router-redux';
import styles from './StaticPages.scss';
import { Grid } from 'react-bootstrap/lib';

@connect(
  () => ({}),
  {pushState: push})

export default class TermsOfUse extends Component {
  static propTypes = {
    pushState: PropTypes.func.isRequired
  };

  handleMenuClick() {
    this.props.pushState('/register');
  }

  render() {
    return (
      <div>
        <Header isRed={true} buttonText={'Back'} pageCaption={<span>Terms Of Use</span>} btnAction={this.handleMenuClick.bind(this)} />
        <Grid>
         <div className={styles.agreementContent}>
            <h2>TERMS OF USE</h2>
            <p>Thank you for your interest in this application for your mobile device (the “App”) provided to you by Tso Delivery, LLC. (“Tso Chinese Delivery” or “us”), and our website at www.tsodelivery.com (the “Site”), as well as all related websites and other services provided by us and on which a link to these Terms of Use is displayed (collectively, together with the App and Site, our “Service”). These Terms of Use (collectively, “Terms”), as may be updated from time to time, govern your access and use of the Service. These Terms are a legally binding contract between you and Tso Chinese Delivery regarding your access to and use of the Service. You may request a copy of these Terms by emailing us at privacy@tsodelivery.com.</p>
            <br/>
            <p>PLEASE READ THESE TERMS CAREFULLY. BY DOWNLOADING, INSTALLING, OR OTHERWISE ACCESSING OR USING THE APP OR OTHER PARTS OF THE SERVICE, YOU AGREE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE, YOU MAY NOT USE ANY PART OF THE SERVICE.</p>
            <br/>
            <p>You acknowledge and agree that, as provided in greater detail in these Terms:</p>
            <br/>
            <p>the App is licensed, not sold to you, and you may access and use the Service only as set forth in these Terms;</p>
            <br/>
            <p>your access and use of the Service may be subject to separate third party terms of service and fees, including without limitation the terms of service and data, SMS,MMS, and other fees of your mobile network operator (the “Carrier”) and the terms of Apple, Inc. (“Apple”), all of which are your sole responsibility;</p>
            <br/>
            <p>you consent to the collection and use of your personally identifiable information and information about your location in accordance with the Tso Chinese Delivery Privacy Policy, including without limitation the collection of location information;</p>
            <br/>
            <p>the Service is provided “as is” without warranties of any kind and Tso Chinese Delivery’s liability to you is limited;</p>
            <br/>
            <p>disputes arising hereunder will be resolved by binding arbitration, AND BY ACCEPTING THESE TERMS, YOU AND TSO CHINESE DELIVERY ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION. YOU AGREE TO GIVE UP YOUR RIGHT TO GO TO COURT to assert or defend your rights under this contract (except for matters that may be taken to small claims court). Your rights will be determined by a NEUTRAL ARBITRATOR and NOT a judge or jury and your claims cannot be brought as a class action. Please review the arbitration agreement below for the details regarding your agreement to arbitrate any disputes with Tso Chinese Delivery;</p>
            <br/>
            <p>the App requires access to the following services on your mobile device: internet; if you are using the App on an iOS-based device, you agree to and acknowledge the “Notice Regarding Apple”, below.</p>
            <br/>
            <p>Service Overview</p>
            <br/>
            <p>The Service provides users of the Service the ability to order food for delivery to users’ homes and businesses.</p>
            <br/>
            <p>Eligibility</p>
            <br/>
            <p>You must be at least thirteen (13) years of age to use the Service. By agreeing to these Terms, you represent and warrant to us: (i) that you are at least thirteen (13) years of age; (ii) that you have not previously been suspended or removed from the Service; and (iii) that your registration and your use of the Service is in compliance with any and all applicable laws and regulations. If you are using the Service on behalf of an entity, organization, or company, you represent and warrant that you have the authority to bind such organization to these Terms and you agree to be bound by these Terms on behalf of such organization.</p>
            <br/>
            <p>Accounts and Registration</p>
            <br/>
            <p>Tso Chinese Delivery Account. To access most features of the Service, you must register for an account. When you register for an account, you may be required to provide us with some information about yourself (such as your name, email address or other contact information, as well as your credit card number, phone number and delivery address). We do not store your credit card information. You agree that the information you provide to us is accurate and that you will keep it accurate and up-to-date at all times. When you register, you will be asked to provide a password. You are solely responsible for maintaining the confidentiality of your account and password. You agree to accept responsibility for all activities that occur under your account. If you have reason to believe that your account is no longer secure, then you must immediately notify us at hello@tsodelivery.com.</p>
            <br/>
            <p>Third Party Accounts</p>
            <br/>
            <p> In order to download the App, you may be required by third parties who are providing services in connection with the App, such as Apple, Inc. and Google Inc. (each, a “Service Provider”) to create an account. You are solely responsible for maintaining the security of any logins, passwords, or other credentials that you select or that are provided to you to access your account with any Service Provider. Your access and use of any account with a Service Provider, including in connection with the Service, is subject to any terms, conditions, and policies, including privacy policies, of that Service Provider. Tso Chinese Delivery is not responsible for any act or omission of any Service Provider.</p>
            <br/>
            <p>Cancellation Policy</p>
            <br/>
            <p> Due to the nature of the service, orders are considered final as soon as they are placed.  Exceptions may be considered on a case-by-case basis. If you would like to cancel an order, please e-mail us at hello@tsodelivery.com.</p>
            <br/>
            <p>License to the App</p>
            <br/>
            <p>Subject to your complete and ongoing compliance with all the terms and conditions set forth in these Terms (including without limitation payment of any applicable fees and compliance with all license restrictions), Tso Chinese Delivery grants you (1) a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to use one copy of the App downloaded directly from Tso Chinese Delivery or from a legitimate marketplace (such as the Apple App Store), solely in object code format and solely for your personal use for lawful purposes, on a single compatible mobile device that you own or control; and (2) permission to access and use the Service, only for your personal use, and solely through the use of a licensed copy of the App. You may not reproduce, distribute, publicly display, or publicly perform the App or any part of the Service. Except if, and solely to the extent that, such a restriction is impermissible under applicable law, you may not (a) decompile, reverse engineer, or otherwise access or attempt to access the source code for the App, or make or attempt to make any modification to or derivative work of the App; or (b) interfere with or circumvent any feature of the App, including without limitation any security or access control mechanism. You may not use the App or the Service for any purpose other than a purpose for which the App and the Service are expressly designed. The term App, as used herein, includes any update or modification to the App made available to you by Tso Chinese Delivery (unless provided with separate terms). If you are prohibited under applicable law from using the App or the Service, you may not use them.</p>
            <br/>
            <p>Access to the Service; Third Party Fees</p>
            <br/>
            <p>Tso Chinese Delivery does not provide you with the equipment to access or use the Service. You are responsible for all fees charged by third parties to access and use the Service (e.g., charges by Carriers). Without limiting the foregoing, you are solely responsible for the payment of all applicable fees associated with any Carrier service plan you use in connection with your access and use of the Service (such as voice, data, SMS, MMS, roaming, other applicable fees charged by the Carrier). Accordingly, you should use care in selecting a service plan offered by your Carrier. If your device is lost or stolen, you must notify Tso Chinese Delivery immediately to suspend services.</p>
            <br/>
            <p>User Content</p>
            <br/>
            <p>User Content Generally. Certain features of the Service may permit users to post content, including messages, reviews, photos, video, images, folders, data, text, and other types of works (collectively, “User Content”) and to publish User Content on or through the Service. You retain copyright and any other proprietary rights that you may hold in the User Content that you post to the Service.</p>
            <br/>
            <p>Limited License Grant to Tso Chinese Delivery. By posting or publishing User Content, you grant Tso Chinese Delivery a worldwide, non-exclusive, royalty-free right and license (with the right to sublicense) to host, store, transfer, display, perform, reproduce, modify, and distribute your User Content, in whole or in part, in any media formats and through any media channels (now known or hereafter developed). Any such use of your User Content by Tso Chinese Delivery may be without any compensation paid to you.</p>
            <br/>
            <p>Limited License Grant to Other Users. By posting and sharing User Content with another user of the Service, you hereby grant that user a non-exclusive license to access and use such User Content as permitted by these Terms and the functionality of the Service.</p>
            <br/>
            <p>User Content Representations and Warranties. You are solely responsible for your User Content and the consequences of posting or publishing User Content. By posting and publishing User Content, you affirm, represent, and warrant that:</p>
            <br/>
            <p>you are the creator and owner of, or have the necessary licenses, rights, consents, and permissions to use and to authorize Tso Chinese Delivery and users of the Service to use and distribute your User Content as necessary to exercise the licenses granted by you in this section and in the manner contemplated by Tso Chinese Delivery and these Terms; and</p>
            <br/>
            <p>your User Content, and use of your User Content as contemplated by these Terms, does not and will not: (i) infringe, violate, or misappropriate any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right; or (ii) slander, defame, libel, or invade the right of privacy, publicity or other property rights of any other person.</p>
            <br/>
            <p>User Content Disclaimer. We are under no obligation to edit or control User Content that you or other users post or publish, and will not be in any way responsible or liable for User Content. Tso Chinese Delivery may, however, at any time and without prior notice, screen, remove, edit, or block any User Content that in our sole judgment violates these Terms or is otherwise objectionable. You understand that when using the Service you will be exposed to User Content from a variety of sources and acknowledge that User Content may be inaccurate, offensive, indecent or objectionable. You agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against Tso Chinese Delivery with respect to User Content. We expressly disclaim any and all liability in connection with User Content. If notified by a user or content owner that User Content allegedly does not conform to these Terms, we may investigate the allegation and determine in our sole discretion whether to remove the User Content, which we reserve the right to do at any time and without notice. For clarity, Tso Chinese Delivery does not permit copyright-infringing activities on the Service.</p>
            <br/>
            <p>Digital Millennium Copyright Act</p>
            <br/>
            <p>DMCA Notification. We comply with the provisions of the Digital Millennium Copyright Act applicable to internet service providers (17 U.S.C. §512, as amended). If you have any complaints with respect to material posted on the Service, you may contact our Designated Agent at the following address:</p>
            <br/>
            <p>Tso Chinese Delivery, Inc.<br/>3909 N IH35 Ste E-5<br/>Austin, TX<br/>78722</p>
            <br/>
            <p>Email: hello@tsodelivery.com</p>
            <br/>
            <p>Any notice alleging that materials hosted by or distributed through the Service infringe intellectual property rights must include the following information:</p>
            <br/>
            <ul>
            <li>an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other right being infringed;</li>
            <li>a description of the copyrighted work or other intellectual property that you claim has been infringed;</li>
            <li>a description of the material that you claim is infringing and where it is located on the Service; your address, telephone number, and email address;</li>
            <li>a statement by you that you have a good faith belief that the use of the materials on the Service of which you are complaining is not authorized by the copyright owner, its agent, or the law; and</li>
            <li>a statement by you that the above information in your notice is accurate and that, under penalty of perjury, you are the copyright or intellectual property owner or authorized to act on the copyright or intellectual property owner’s behalf.</li>
            </ul>
            <br/>
            <p>Repeat Infringers. Tso Chinese Delivery will promptly terminate without notice the accounts of users that are determined by Tso Chinese Delivery to be “repeat infringers.” A repeat infringer is a user who has been notified of infringing activity more than twice and/or has had User Content removed from the Service more than twice.</p>
            <br/>
            <p>Prohibited Conduct</p>
            <br/>
            <p>By using the Service you agree not to:</p>
            <br/>
            <ul>
            <li>use the Service for any illegal purpose, or in violation of any local, state, national, or international law;</li>
            <li>post, upload, or distribute any User Content or other content that is unlawful, defamatory, libelous, inaccurate, or that a reasonable person could deem to be objectionable, profane, indecent, pornographic, harassing, threatening, embarrassing, hateful, or otherwise inappropriate;</li>
            <li>violate, or encourage others to violate, the rights of third parties, including by infringing or misappropriating third party intellectual property rights;</li>
            <li>interfere with security-related features of the Service, including without limitation by (i) disabling or circumventing features that prevent or limit use or copying of any content, or (ii) reverse engineering or otherwise attempting to discover the source code of any portion of the Service except to the extent that such activity is expressly permitted by applicable law;</li>
            <li>interfere with the operation of the Service or any user’s enjoyment of the Service, including without limitation by (i) uploading or otherwise disseminating viruses, adware, spyware, worms, or other malicious code, (ii) making unsolicited offers or advertisements to other users of the Service, (iii) attempting to collect, personal information about users or third parties without their consent; or (iv) interfering with or disrupting any networks, equipment, or servers connected to or used to provide the Service, or violating the regulations, policies, or procedures of such networks, equipment, or servers;</li>
            <li>perform any fraudulent activity including impersonating any person or entity, claiming false affiliations, accessing the Service accounts of others without permission, or falsifying your age or date of birth;</li>
            <li>sell or otherwise transfer the access granted by these Terms or any Materials (as defined below) or any right or ability to view, access, or use any Materials; or</li>
            <li>attempt to do any of the prohibited acts described in this Section 8, or assist or permit any persons in engaging in any of the acts described in this section.</li>
            </ul>
            <br/>
            <p>Third-Party Services and Linked Websites. Tso Chinese Delivery may provide tools through the Service that enable you to export information, including User Content, to third party services, including through features that allow you to link your account on Tso Chinese Delivery with an account on the third party service, such as Twitter or Facebook, or through our implementation of third party buttons (such as “like” or “share” buttons). By using these tools, you agree that we may transfer such information to the applicable third-party service. Such third party services are not under our control, and we are not responsible for their use of your exported information. The Service may also contain links to third-party websites. Such linked websites are not under our control, and we are not responsible for their content.</p>
            <br/>
            <p>Termination of Use; Discontinuation and Modification of the Service. If you violate any provision of these Terms, your permission to use the Service will terminate automatically. Additionally, Tso Chinese Delivery, in its sole discretion may terminate your user account on the Service or suspend or terminate your access to the Service at any time, with or without notice. We also reserve the right to modify or discontinue the Service at any time (including, without limitation, by limiting or discontinuing certain features of the Service) without notice to you. We will have no liability whatsoever on account of any change to the Service or any suspension or termination of your access to or use of the Service. You may terminate your account at any time by contacting customer service at help@maple.com. If you terminate your account, you will remain obligated to pay all outstanding fees, if any, relating to your access or use of the Service incurred prior to termination. If you or we terminate your account, you must immediately destroy all copies of the App and any part thereof.</p>
            <br/>
            <p>Feedback. If you provide feedback to Tso Chinese Delivery regarding the Service (“Feedback”), you acknowledge that the Feedback is not confidential and you authorize Tso Chinese Delivery to use that Feedback without restriction and without payment to you. Accordingly, you hereby grant to Tso Chinese Delivery a nonexclusive, royalty-free, fully-paid, perpetual, irrevocable, transferable, and fully sublicensable right to use the Feedback in any manner and for any purpose.</p>
            <br/>
            <p>Privacy Policy; Additional Terms</p>
            <br/>
            <p>Privacy Policy. Please read the Tso Chinese Delivery Privacy Policy carefully for information relating to our collection, use, storage and disclosure of your personal information. The Tso Chinese Delivery Privacy Policy is hereby incorporated by reference into, and made a part of, these Terms.</p>
            <br/>
            <p>Additional Terms. Your access and use of the Service is subject to any and all additional terms, policies, rules, or guidelines applicable to the Service or certain features of the Service that we may post on or link to on the Service (the “Additional Terms”), such as end-user license agreements for any downloadable applications that we may offer, or rules applicable to particular features or content on the Service. All such Additional Terms are hereby incorporated by reference into, and made a part of, these Terms.</p>
            <br/>
            <p>Modification of these Terms. We reserve the right, at our discretion, to change these Terms on a going-forward basis at any time. Please check these Terms periodically for changes. If a change to these Terms materially modifies your rights or obligations, you will be required to accept such modified terms in order to continue to use the Service. Material modifications are effective upon your acceptance of such modified Terms. Immaterial modifications are effective upon publication. For the avoidance of doubt, disputes arising under these Terms will be resolved in accordance with these Terms in effect at the time the dispute arose.</p>
            <br/>
            <p>Ownership; Proprietary Rights. The Service is owned and operated by Tso Chinese Delivery. The visual interfaces, graphics, design, compilation, information, data, computer code (including source code or object code), products, App(s), services, and all other elements of the Service (the “Materials”) provided by Tso Chinese Delivery are protected by all relevant intellectual property and proprietary rights and applicable laws. All Materials contained in the Service are the property of Tso Chinese Delivery or our third-party licensors. Except as expressly authorized by Tso Chinese Delivery, you may not make use of the Materials. Tso Chinese Delivery reserves all rights to the Materials not granted expressly in these Terms.</p>
            <br/>
            <p>Indemnity. You agree that you will be responsible for your use of the Service, and you agree to defend, indemnify, and hold harmless Tso Chinese Delivery and its affiliates and their respective officers, directors, employees, consultants, Service Providers and agents (collectively, the “Tso Chinese Delivery Entities”) from and against any and all claims, liabilities, damages, losses, and expenses, including reasonable attorneys’ fees and costs, arising out of or in any way connected with (i) your access to, use of, or alleged use of the Service; (ii) your violation of these Terms or any representation, warranty, or agreements referenced in these Terms, or any applicable law or regulation; (iii) your violation of any third-party right, including without limitation any intellectual property right, publicity, confidentiality, property or privacy right; or (iv) any disputes or issues between you and any third party. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you (and without limiting your indemnification obligations with respect to such matter), and in such case, you agree to cooperate with our defense of such claim.</p>
            <br/>
            <p>Disclaimers; No Warranties</p>
            <br/>
            <p>THE SERVICE AND ALL MATERIALS AND CONTENT AVAILABLE THROUGH THE SERVICE ARE PROVIDED “AS IS” AND ON AN “AS AVAILABLE” BASIS, WITHOUT WARRANTY OR CONDITION OF ANY KIND, EITHER EXPRESS OR IMPLIED. THE Tso Chinese Delivery ENTITIES SPECIFICALLY (BUT WITHOUT LIMITATION) DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, RELATING TO THE SERVICE AND ALL MATERIALS AND CONTENT AVAILABLE THROUGH THE SERVICE, INCLUDING BUT NOT LIMITED TO (i) ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, OR NON-INFRINGEMENT; AND (ii) ANY WARRANTIES ARISING OUT OF COURSE OF DEALING, USAGE, OR TRADE. THE Tso Chinese Delivery ENTITIES DO NOT WARRANT THAT THE SERVICE OR ANY PART OF THE SERVICE, OR ANY MATERIALS OR CONTENT OFFERED THROUGH THE SERVICE, WILL BE UNINTERRUPTED, SECURE, OR FREE OF ERRORS, VIRUSES, OR OTHER HARMFUL COMPONENTS, AND DO NOT WARRANT THAT ANY OF THE FOREGOING WILL BE CORRECTED.</p>
            <br/>
            <p>NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM THE SERVICE OR ANY MATERIALS OR CONTENT AVAILABLE ON OR THROUGH THE SERVICE WILL CREATE ANY WARRANTY REGARDING ANY OF THE Tso Chinese Delivery ENTITIES OR THE SERVICE THAT IS NOT EXPRESSLY STATED IN THESE TERMS. YOU ASSUME ALL RISK FOR ALL DAMAGES THAT MAY RESULT FROM YOUR USE OF OR ACCESS TO THE SERVICE, YOUR DEALINGS WITH OTHER SERVICE USERS, AND ANY MATERIALS OR CONTENT AVAILABLE THROUGH THE SERVICE. YOU UNDERSTAND AND AGREE THAT YOU USE THE SERVICE, AND YOU USE, ACCESS, DOWNLOAD, OR OTHERWISE OBTAIN MATERIALS OR CONTENT THROUGH THE SERVICE, AND ANY ASSOCIATED SITES OR SERVICES AT YOUR OWN DISCRETION AND RISK, AND AS BETWEEN YOU AND Tso Chinese Delivery, YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR PROPERTY (INCLUDING YOUR COMPUTER SYSTEM USED IN CONNECTION WITH THE SERVICE) OR LOSS OF DATA OR ANY OTHER LOSS THAT RESULTS FROM THE USE OF THE SERVICE OR THE DOWNLOAD OR USE OF SUCH MATERIALS OR CONTENT. SOME JURISDICTIONS MAY PROHIBIT A DISCLAIMER OF WARRANTIES AND YOU MAY HAVE OTHER RIGHTS THAT VARY FROM JURISDICTION TO JURISDICTION.</p>
            <br/>
            <p>Limitation of Liability</p>
            <br/>
            <p>IN NO EVENT WILL THE TSO CHINESE DELIVERY ENTITIES BE LIABLE TO YOU FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES) ARISING OUT OF OR RELATING TO YOUR ACCESS TO OR USE OF, OR YOUR INABILITY TO ACCESS OR USE, THE SERVICE OR ANY MATERIALS OR CONTENT ON THE SERVICE, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STATUTE OR ANY OTHER LEGAL THEORY, WHETHER OR NOT THE TSO CHINESE DELIVERY ENTITIES HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE. YOU AGREE THAT THE AGGREGATE LIABILITY OF THE Tso Chinese Delivery ENTITIES TO YOU FOR ANY AND ALL CLAIMS ARISING OUT OF OR RELATING TO THE USE OF OR ANY INABILITY TO USE THE SERVICE (INCLUDING ANY MATERIALS OR CONTENT AVAILABLE THROUGH THE SERVICE) OR OTHERWISE UNDER THESE TERMS, WHETHER IN CONTRACT, TORT, OR OTHERWISE, IS LIMITED TO THE GREATER OF (i) THE AMOUNTS YOU HAVE PAID TO TSO CHINESE DELIVERY FOR ACCESS TO AND USE OF THE SERVICE IN THE 12 MONTHS PRIOR TO THE CLAIM OR (ii) $100.</p>
            <br/>
            <p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES. ACCORDINGLY, THE ABOVE LIMITATION MAY NOT APPLY TO YOU.</p>
            <br/>
            <p>EACH PROVISION OF THESE TERMS THAT PROVIDES FOR A LIMITATION OF LIABILITY, DISCLAIMER OF WARRANTIES, OR EXCLUSION OF DAMAGES IS TO ALLOCATE THE RISKS UNDER THESE TERMS BETWEEN THE PARTIES. THIS ALLOCATION IS AN ESSENTIAL ELEMENT OF THE BASIS OF THE BARGAIN BETWEEN THE PARTIES. EACH OF THESE PROVISIONS IS SEVERABLE AND INDEPENDENT OF ALL OTHER PROVISIONS OF THESE TERMS. THE LIMITATIONS IN THIS SECTION WILL APPLY EVEN IF ANY LIMITED REMEDY FAILS OF ITS ESSENTIAL PURPOSE.</p>
            <br/>
            <p>Governing Law. These Terms are governed by and construed in accordance with the laws of the State of Texas, without regard to any principles of conflicts of law, and all claims, disputes or disagreements which may arise out of the interpretation, performance or in any way relating to your use of the Service, the Materials and/or other content on the Site or App shall be submitted exclusively to the jurisdiction of the state or federal courts of applicable jurisdiction located in Travis County and State of Texas. To the extent that any lawsuit or court proceeding is permitted hereunder, you and Tso Chinese Delivery acknowledge and agree that you will irrevocably consent and submit to the exclusive personal jurisdiction of those courts for the purpose of litigating any such action; and you will irrevocably waive any jurisdictional, venue or inconvenient forum objections to such court. We operate the Service from our offices in Texas, and we make no representation that Materials included in the Service are appropriate or available for use in other locations.</p>
            <br/>
            <p>General. These Terms, together with the Tso Chinese Delivery Privacy Policy and any other agreements expressly incorporated by reference, constitute the entire and exclusive understanding and agreement between you and Tso Chinese Delivery regarding your use of and access to the Service, and except as expressly permitted above may be amended only by a written agreement signed by authorized representatives of all parties to these Terms. You may not assign or transfer these Terms or your rights hereunder, in whole or in part, by operation of law or otherwise, without our prior written consent. We may assign these Terms at any time without notice. The failure to require performance of any provision will not affect our right to require performance at any time thereafter, nor will a waiver of any breach or default of these Terms or any provision of these Terms constitute a waiver of any subsequent breach or default or a waiver of the provision itself. Use of section headers in these Terms are for convenience only and will not have any impact on the interpretation of particular provisions. If any part of these Terms is held to be invalid or unenforceable, the unenforceable part will be given effect to the greatest extent possible and the remaining parts will remain in full force and effect. Upon termination of these Terms, any provision that by its nature or express terms should survive will survive such termination or expiration.</p>
            <br/>
            <p>Dispute Resolution and Arbitration</p>
            <br/>
            <p>Generally. In the interest of resolving disputes between you and Tso Chinese Delivery in the most expedient and cost effective manner, you and Tso Chinese Delivery agree that any and all disputes arising in connection with these Terms will be resolved by binding arbitration. Arbitration is more informal than a lawsuit in court. Arbitration uses a neutral arbitrator instead of a judge or jury, may allow for more limited discovery than in court, and can be subject to very limited review by courts. Arbitrators can award the same damages and relief that a court can award. Our agreement to arbitrate disputes includes, but is not limited to all claims arising out of or relating to any aspect of these Terms, whether based in contract, tort, statute, fraud, misrepresentation or any other legal theory, and regardless of whether the claims arise during or after the termination of these Terms. YOU UNDERSTAND AND AGREE THAT, BY ENTERING INTO THESE TERMS, YOU AND TSO CHINESE DELIVERY ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION.</p>
            <br/>
            <p>Exceptions. Notwithstanding the preceding paragraph, we both agree that nothing in these Terms will be deemed to waive, preclude, or otherwise limit either of our right to: (i) bring an individual action in small claims court; (ii) pursue enforcement actions through applicable federal, state, or local agencies where such actions are available; (iii) seek injunctive relief in a court of law; or (iv) to file suit in a court of law to address intellectual property infringement claims.</p>
            <br/>
            <p>Arbitrator. Any arbitration between you and Tso Chinese Delivery will be governed by the Commercial Dispute Resolution Procedures and the Supplementary Procedures for Consumer Related Disputes (collectively, “AAA Rules”) of the American Arbitration Association (“AAA”), as modified by these Terms, and will be administered by the AAA. The AAA Rules and filing forms are available online at www.adr.org, by calling the AAA at 1-800-778-7879, or by contacting Tso Chinese Delivery.</p>
            <br/>
            <p>Notice; Process. A party who intends to seek arbitration must first send a written notice of the dispute to the other, by certified mail or Federal Express (signature required), or if we do not have a physical address on file for you, by electronic mail (“Notice”). Tso Chinese Delivery’s address for Notice is: Tso Chinese Delivery, Inc., 3909 N IH35 Ste E-5, Austin, TX, 78722. The Notice must: (i) describe the nature and basis of the claim or dispute; and (ii) set forth the specific relief sought (“Demand”). We agree to use good faith efforts to resolve the claim directly, but if we do not reach an agreement to do so within 30 days after the Notice is received, you or Tso Chinese Delivery may commence an arbitration proceeding. During the arbitration, the amount of any settlement offer made by you or Tso Chinese Delivery must not be disclosed to the arbitrator until after the arbitrator makes a final decision and award, if any. If our dispute is finally resolved through arbitration in your favor, Tso Chinese Delivery will pay you: (a) the amount awarded by the arbitrator, if any; (b) the last written settlement amount offered by Tso Chinese Delivery in settlement of the dispute prior to the arbitrator’s award; or © $1,000.00, whichever is greater.</p>
            <br/>
            <p>Fees. If you commence arbitration in accordance with these Terms, Tso Chinese Delivery will reimburse you for your payment of the filing fee, unless your claim is for greater than $10,000, in which case the payment of any fees will be decided by the AAA Rules. Any arbitration hearings will take place at a location to be agreed upon in Travis County, Texas, provided that if the claim is for $10,000 or less, you may choose whether the arbitration will be conducted: (i) solely on the basis of documents submitted to the arbitrator; (ii) through a non-appearance based telephonic hearing; or (iii) by an in-person hearing as established by the AAA Rules in the county (or parish) of your billing address. If the arbitrator finds that either the substance of your claim or the relief sought in the Demand is frivolous or brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)), then the payment of all fees will be governed by the AAA Rules. In such case, you agree to reimburse Tso Chinese Delivery for all monies previously disbursed by it that are otherwise your obligation to pay under the AAA Rules. Regardless of the manner in which the arbitration is conducted, the arbitrator will issue a reasoned written decision sufficient to explain the essential findings and conclusions on which the decision and award, if any, are based. The arbitrator may make rulings and resolve disputes as to the payment and reimbursement of fees or expenses at any time during the proceeding and upon request from either party made within 14 days of the arbitrator’s ruling on the merits.</p>
            <br/>
            <p>No Class Actions. YOU AND TSO CHINESE DELIVERY AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. Further, unless both you and Tso Chinese Delivery agree otherwise, the arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of a representative or class proceeding.</p>
            <br/>
            <p>Modifications. If Tso Chinese Delivery makes any future change to this arbitration provision (other than a change to Tso Chinese Delivery’s address for Notice), you may reject any such change by sending us written notice within 30 days of the change to Tso Chinese Delivery’s address for Notice, in which case your account with Tso Chinese Delivery will immediately be terminated and this arbitration provision, as in effect immediately prior to the amendments you reject will survive.</p>
            <br/>
            <p>Enforceability. If any part of this section or if the entirety of this section is found to be unenforceable, then the entirety of this section will be null and void and, in that case, the parties agree that the exclusive jurisdiction and venue described above will govern any action arising out of or related to these Terms.</p>
            <br/>
            <p>Consent to Electronic Communications. By using the Service, you consent to receiving certain electronic communications from us as further described in our Privacy Policy. Please read our Privacy Policy to learn more about your choices regarding our electronic communications practices. You agree that any notices, agreements, disclosures, or other communications that we send to you electronically will satisfy any legal communication requirements, including that such communications be in writing.</p>
            <br/>
            <p>Contact Information. The services hereunder are offered by Tso Chinese Delivery, located at Tso Chinese Delivery, 3909 N IH35 Ste E-5, Austin, TX 78722. You may contact us by sending correspondence to the foregoing address or by emailing us at hello@tsodelivery.com.</p>
            <br/>
            <p>Special Terms Regarding Apple. If you are downloaded the App from the Apple, Inc. (“Apple”) App Store or if you are using the App on an iOS-based device, you acknowledge that you have read, understood, and agree to the following notice regarding Apple. Your use of the software must at all times be in accordance with the Usage Rules set forth in the Apple, Inc. App Store Terms of Service. These Terms are between you and Tso Chinese Delivery only, not with Apple, and Apple is not responsible for the Service and the content thereof. These Terms are not intended to provide for usage rules for software that are less restrictive than the Usage Rules set forth for “Licensed Applications” in, or that otherwise conflict with, the Apple, Inc. App Store Terms of Service. Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the Service. In the event of any failure of the Service to conform to any applicable warranty, you may notify Apple and Apple will refund any applicable purchase price for the App to you; and, to the maximum extent permitted by applicable law, Apple has no other warranty obligation whatsoever with respect to the Service. Apple is not responsible for addressing any claims by you or any third party relating to the Service or your possession and/or use of the Service, including, but not limited to: (i) product liability claims; (ii) any claim that the Service fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation. Apple is not responsible for the investigation, defense, settlement and discharge of any third party claim that the Service and/or your possession and use of the App infringe that third party’s intellectual property rights. You hereby represent and warrant that (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country; and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties. You agree to comply with any applicable third party terms when using the Service. Apple, and Apple’s subsidiaries, are third party beneficiaries of these Terms, and upon your acceptance of these Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as a third party beneficiary of these Terms.</p>
            <br/>

        </div>
        </Grid>
      </div>
    );
  }
}
